### PR TITLE
Config improvements

### PR DESCRIPTION
**Pull request by Theodlz**
* remove the `config.defaults.yaml` from `extensions/skyportal`
* instead, load the baselayer default config -> skyportal default config -> icare default config -> icare user defined config (optional), each overwriting the previous config files for the keys that they share. The resulting "complete" config is written as the config.yaml used in `patched_skyportal`.
* add a icare_prod.sh script to use on the IJCLAB machine, as the modifications that were made to the `icare.sh` script to make it work in prod broke the CI.
* updated the layout of the `extensions/skyportal` dir to reflect the changes made on main, fixed the imports where needed.

### CODE REVIEW

**Comment by Theodlz** [comment]
CI should run here, and if not then I need to fix some things before merging @JulienPeloton!

**Comment by JulienPeloton** [comment]
Thanks @Theodlz -- the CI fails with various errors. I'll let you have a look?

**Comment by Theodlz** [comment]
On it @JulienPeloton. Some the of the CI might fail anyway (some tests are flaky), but as long as it actually runs and not everything is red (which tells us that the app starts properly), I think it's enough.

**Comment by Theodlz** [comment]
@JulienPeloton bunch of failures in the CI but the app does boot up properly and things are running. I'll investigate the failures later but I doubt any of them are caused by this PR, it's been there but wasn't visible since the CI was outdated and literally not running.

**Pull request merged**
